/*
    In Database Management System (DBMS), we need to generate the keys for records created. In many cases, a key is generated by
    generating a non-negative integer and its standardized under a string with fixed length L (by filling characters 0 at the beginning 
    of the integer util the length is equal to L)
    Given a positive integer n and L, and a sequence of integers a1, a2, ..., an. Write a program for generating corresponding keys k1, k2, ..., kn.
*/

#include<bits/stdc++.h>
using namespace std;
#define INF 1e9
#define MAX 1000009
#define ll long long
#define MOD 1000000009

int n, L;
vector<int> a;

int main() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);

    cin >> n >> L;
    for(int i = 0; i < n; i++) {
        int x;
        cin >> x;
        a.push_back(x);
    }

    for(int i = 0; i < n; i++) {
        string s = to_string(a[i]);
        while(s.length() < L) {
            s = "0" + s;
        }
        cout << s << endl;
    }

    return 0;
}